In [3]:
%matplotlib notebook

In [4]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import colors
from numpy import std, pad, amax, abs
from numpy.random import normal
from numpy.fft import fftshift, ifftshift, fft2, ifft2 
from cv2 import imshow as cv2_imshow
#from google.colab.patches import cv2_imshow

In [5]:
# Filenames
filename = './pics/lenna.jpg'
test_filenames = ['./pics/barraxx.bmp', './pics/BDBOB.jpg',
                  './pics/pru2old.bmp']

# Show original image

In [6]:
original = cv.imread(filename=filename, flags=cv.IMREAD_COLOR)
cv.imshow(winname = 'original', mat = original)
cv.waitKey(0)
cv.destroyAllWindows()

# Blur + Noise

In [7]:
def noisy_gauss(image, snr=20):
      row, col, ch = image.shape
      sigma_image = std(image)
      sigma_noise = np.sqrt(sigma_image**2 * 10**(-snr/10))
      noise = normal(loc=0.0, scale=sigma_noise, size=image.shape)
      noisy = image + noise
      noisy = np.where(noisy < 0,  0, noisy)
      noisy = np.where(noisy > 255, 255, noisy)
      noisy = noisy.astype(dtype=np.uint8)
      return noisy, sigma_noise

In [8]:
kernel_shape = (5, 5)
lenna_blur = cv.blur(src=original, ksize=(5, 5))
lenna_blur_noise, noise_sigma = noisy_gauss(image=lenna_blur, snr=10)

In [9]:
cv2_imshow('lena blured and noisy',lenna_blur_noise)
cv.waitKey(0)
cv.destroyAllWindows()

# Wiener

In [10]:
kernel = 1 / kernel_shape[0] / kernel_shape[1]
kernel *= np.ones(shape=kernel_shape)

In [21]:
def recover(img, h, sn=None, wiener_inverse=False, show = True):

  a, b, _ = img.shape
  padded_kernel = np.zeros(shape=(a, b))
  c, d = h.shape
  padded_kernel[a//2 - c//2:a//2 + c//2 +1, b//2 - d//2: b//2 + d//2 +1] = h
  centered_fft2_kernel = fftshift(fft2(fftshift(padded_kernel)))
  centered_fft2_kernel += 1.2
  h = centered_fft2_kernel

  channels = []
  for channel in cv.split(img):
    channel = fftshift(fft2(channel))
    if wiener_inverse:
      sf = channel
      clean_lena = channel / h * np.abs(h)**2 / (np.abs(h)**2 + sn / sf)
    else:
      clean_lena = channel / h

    # filtered image ifft2 and normalize to unity
    clean_lena = np.abs(ifft2(ifftshift(clean_lena)))
    maximum = amax(clean_lena)
    clean_lena /= maximum
    clean_lena *= 255
    clean_lena = clean_lena.astype(np.uint8)
    channels.append(clean_lena)

  if len(channels) > 1:
    clean_lena = cv.merge(channels)
  else:
    clean_lena = channels
  newww = np.hstack((clean_lena, img))
  if show:
        cv2_imshow('recovery', newww)
        cv.waitKey(0)
        cv.destroyAllWindows()
  return clean_lena

In [12]:
noise_shape = (lenna_blur_noise.shape[0], lenna_blur_noise.shape[1])
noise = np.ones(shape=noise_shape) * noise_sigma**2

wiener_result = recover(img=lenna_blur_noise, h=kernel, sn=noise, wiener_inverse=True)

# Inverse Filtering

In [13]:
inverse_result = recover(img=lenna_blur_noise, h=kernel, wiener_inverse=False)

In [14]:
stacked = np.hstack((wiener_result, inverse_result))
cv2_imshow('wiener vs inverse_simple', stacked)
cv.waitKey(0)
cv.destroyAllWindows()
print('Wiener vs Inverse')

Wiener vs Inverse


In [15]:
def estimate_blur_kernel(img):
  #estimated = None
  estimated = (1/9)*np.ones((3, 3))
  return estimated

In [16]:
for name in test_filenames:
  img = cv.imread(name)
  if img.any() == None:
        print("invalid image")
  noise_shape = (img.shape[0], img.shape[1])
  # assuming noise_sigma based on lena... should change the estimated value
  # based on the new image 
  noise = np.ones(shape=noise_shape) * noise_sigma**2

  kernel = estimate_blur_kernel(img)
  wiener_result = recover(img=img, h=kernel, sn=noise, wiener_inverse=True)
  inverse_result = recover(img=img, h=kernel, wiener_inverse=False)
  stacked = np.hstack((wiener_result, inverse_result))
  cv2_imshow('wiener vs inverse', stacked)
  cv.waitKey(0)
  cv.destroyAllWindows()
  print('Wiener vs Inverse')

Wiener vs Inverse
Wiener vs Inverse
Wiener vs Inverse


### Blind Deconvolution

Blind Deconvolution (Deconvolución a ciegas) consiste en un algoritmo que reconstruye la imagen sin necesidad de tener el modelo exacto de la función "PSF" (es por esto que se le da el nombre de "a ciegas"). El algortimo parte de una función PSF "a priori", o supone una forma de función PSF, pero luego la ajusta según la imagen de entrada. Para ajustar la función PSF, el algoritmo suele usar las secciones más brillantes de la imagen, que se vieron menos afectadas por el nivel de ruido.
Para la implementación, se utilizó la función "deconvblind" de Matlab, a la que se la paso la sencilla función PSF a priori como una matriz de 12x12 de unos. Con esto logro obtenerse resultados aceptables.

In [17]:
matlab_code_img = cv.imread('deconvCodeMATLAB.png')
#print(matlab_code_img)
cv.imshow('matlab code deconvblind', matlab_code_img)
cv.waitKey(0)
cv.destroyAllWindows()

In [18]:
in_image_blind = cv.imread('image_in_deconvblind.bmp') 
out_image_blind = cv.imread('image_out_deconvblind.bmp') 
in_out_images = np.hstack((in_image_blind, out_image_blind))
cv.imshow('in image -LEFT- vs out -RIGHT-', in_out_images)
cv.waitKey(0)
cv.destroyAllWindows()

### Motion Blur

Para simular el motion blur que degrada una imagen debido a un movimiento de una cámara al momento de tomar la foto, se realizan kernels con unos en una columna (en caso de motion vertical) o en una fila (en caso de blur horizonral).

In [45]:
kernel_h_motion = np.zeros((5, 5))
kernel_v_motion = np.zeros((5, 5))

k = 1 / 11
kernel_h_motion[0, :] = k
kernel_h_motion[4, :] = k
kernel_h_motion[2, 2] = k

kernel_v_motion[:, 0] = k
kernel_v_motion[:, 4] = k
kernel_v_motion[2, 2] = k



print(kernel_v_motion)
print(kernel_h_motion)

[[0.09090909 0.         0.         0.         0.09090909]
 [0.09090909 0.         0.         0.         0.09090909]
 [0.09090909 0.         0.09090909 0.         0.09090909]
 [0.09090909 0.         0.         0.         0.09090909]
 [0.09090909 0.         0.         0.         0.09090909]]
[[0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.09090909 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.09090909 0.09090909 0.09090909 0.09090909 0.09090909]]


#### Vertical Motion

In [50]:
original = cv.imread(filename=filename, flags=cv.IMREAD_COLOR)
vertical_moved = cv.filter2D(original, -1, kernel_v_motion)
noise = np.ones(shape=(256, 256)) * (noise_sigma/10)**2
#vertical_recovered = recover(vertical_moved, kernel_v_motion, sn= noise, wiener_inverse=True, show = False)
vertical_recovered = recover(vertical_moved, kernel_v_motion, sn= noise, wiener_inverse=False, show = False)
in_out_images = np.hstack((original, vertical_moved, vertical_recovered))
cv.imshow('original - LEFT- moved image -CENTER- vs recovered -RIGHT-', in_out_images)
cv.waitKey(0)
cv.destroyAllWindows()

#### Horizontal Motion

In [51]:

horizontal_moved = cv.filter2D(original, -1, kernel_h_motion)
noise = np.ones(shape=(256, 256)) * (noise_sigma/10)**2
#horizontal_recovered = recover(horizontal_moved, kernel_h_motion, sn= noise, wiener_inverse=True, show = False)
horizontal_recovered = recover(horizontal_moved, kernel_h_motion, sn= noise, wiener_inverse=False, show = False)
in_out_images = np.hstack((original, horizontal_moved, horizontal_recovered))
cv.imshow('original - LEFT- moved image -CENTER- vs recovered -RIGHT-', in_out_images)
cv.waitKey(0)
cv.destroyAllWindows()